# Generated by Django 3.2.12 on 2022-03-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='cin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnels.personnel'),
        ),
    ]
