# Generated by Django 3.2.12 on 2022-03-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_auto_20220318_2301'),
        ('presence', '0002_alter_presence_cin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='nb_heure',
            new_name='nb_heures',
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('cin', 'nb_heures')},
        ),
    ]
