# Generated by Django 3.2.12 on 2022-03-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_auto_20220318_2301'),
        ('presence', '0003_auto_20220318_2307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('cin', 'date_entree')},
        ),
    ]
