# Generated by Django 3.2.12 on 2022-03-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnels', '0002_auto_20220318_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('cin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnels.personnel')),
            ],
            options={
                'unique_together': {('cin', 'date_debut')},
            },
        ),
    ]
